
name = "zenith-wallet"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "build/client"

[[d1_databases]]
binding = "DB"
database_name = "zenith-wallet-db"
database_id = "2d5100fd-46da-4c87-b132-94c79d75a2d6"
